### ISSUE TITLE
Cannot bounce Cheffile.lock

### ISSUE THREAD

**Issue by lackac** [applicationsonline/librarian#10]
I get this error when I try to run `librarian-chef install` after adding a new cookbook to the `Cheffile` in a repo where I have already run this once.

The `Cheffile`:

``` ruby
#!/usr/bin/env ruby
#^syntax detection

git 'git://github.com/opscode/cookbooks'

%w(
  chef-client build-essential users sudo logrotate rsync zsh git vim tmux
  aws
).each { |cb| cookbook(cb) }
# NOTE: 'aws' was the new piece added before the command failed

cookbook 'mongodb', :git => "git://github.com/edelight/cookbooks"
```

The output with verbose turned on: https://gist.github.com/97c51a0e98b076b36d50

**Comment by lackac** [comment]
FYI, this can be resolved by running `librarian-chef install --clean=true`, but I still think this is an issue.

**Comment by yfeldblum** [comment]
Thanks for reporting this issue!

It looks like, after performing the resolve, librarian wants to write out the opscode/cookbooks git-source into the lockfile twice. That shouldn't be happening....
