### ISSUE TITLE
Does outdated work for cookbooks where git is used for the source?

### ISSUE THREAD

**Issue by axsuul** [applicationsonline/librarian#101]
I have a few cookbooks I'm pointing out like so

```
cookbook 'monit', git: 'https://github.com/axsuul/cookbook-monit'
```

If I update the version in the cookbook repo (within `metadata.rb`) and then proceed to run `librarian-chef outdated`, it doesn't show up. Looking through the source, it appears to `git reset --hard` each of the git repos in the cache but that's it. No `git pull` appears to be performed. Is this intended behavior?

**Comment by yfeldblum** [comment]
To answer the question directly and specifically, this is not currently supported.

The basic purpose of `outdated` was to list which cookbooks have new releases out.

At any rate, the meaning of `outdated` for git-sourced cookbooks is a little fuzzy. Does it mean a new version - and if so, how will it discover the new version? Does it mean a new head in the branch?

**Comment by axsuul** [comment]
A newer version would mean the latest commit's sha1 hash has changed. To get the latest commit's sha1 hash

```
$ git ls-remote <URL>
```

**Comment by axsuul** [comment]
Would you accept a pull request to support this?

**Comment by yfeldblum** [comment]
Yes.

**Comment by yfeldblum** [comment]
The implementation should probably do the same first step as is done when updating: fetch all the remotes and then compare the pinned sha to the latest sha in the same ref.

**Comment by axsuul** [comment]
Cool, thanks for the heads up!

**Comment by cjerdonek** [comment]
I was also hit by this today when using `librarian-chef` for the first time.  It confused me that `librarian-chef outdated` didn't recognize that one of my cookbooks wasn't using the latest commit.  At the least, the expected behavior of `outdated` should probably be documented somewhere in this regard.  Was this issue meant to be reopened?  It seems like @yfeldblum was open to some change.

**Comment by yfeldblum** [comment]
The original post in this issue is a question, which I answered. So _this_ issue is closed because it is narrow and resolved.

If someone wants to open a _related_ issue on the subject, proposing a change and even offering a patch, that would be cool.
