### ISSUE TITLE
Customize cookbooks dir name

### ISSUE THREAD

**Issue by patcon** [applicationsonline/librarian#102]
Chef allows multiple cookbook directories. Varying librarian's `cookbooks/` directory name to make it self-documenting would be helpful. ie. `1-cookbooks-external` or whatever makes sense in any person's context. ([In my case](https://github.com/myplanetdigital/ariadne), to make the cookbook origin and override order evident.)

Cheers!

**Comment by yfeldblum** [comment]
You can [customize](https://github.com/applicationsonline/librarian#configuration) the path Librarian-Chef installs cookbooks to.

```
librarian-chef install --path 1-cookbooks-external
```

**Comment by patcon** [comment]
My hero!
