### ISSUE TITLE
[Suggestion] discontinue librarian in favor of Berkshelf

### ISSUE THREAD

**Issue by vitalis** [applicationsonline/librarian#108]

**Comment by taqtiqa-mark** [comment]
This is likely to come up again... there are good reasons to use librarian-chef, at the time of writing, from berkshelf.com:
- "Berkshelf stores every version of a cookbook that you have ever installed."
- "This central location is not the typical pattern of cookbook storage"
- "do not treat The Berkshelf as just another entry in your Chef::Config#cookbooks_path"

See [also](http://christian-trabold.de/librarian-chef-vs-berkshelf)

**Comment by yfeldblum** [comment]
Not a [suggestion].
