### ISSUE TITLE
librarian-chef update fails if there is a whitespace in chef-repo path.

### ISSUE THREAD

**Issue by threeturn** [applicationsonline/librarian#11]
SSIA.

andrea:chef-repo andreag$ librarian-chef update
tar: Error opening archive: Failed to open '/Users/andreag/Documents/Aptana'
/Users/andreag/.rvm/rubies/ruby-1.8.7-p352/lib/ruby/1.8/fileutils.rb:506:in `rename': No such file or directory - /Users/andreag/Documents/Aptana Studio 3 Workspace/chef-repo/tmp/librarian/cache/source/chef/site/877777683730772c36b1e6a3fc3aa2c3/mongodb/mongodb or /Users/andreag/Documents/Aptana Studio 3 Workspace/chef-repo/tmp/librarian/cache/source/chef/site/877777683730772c36b1e6a3fc3aa2c3/mongodb/ddb10eb171f8093fd208b02b177f6214/package (Errno::ENOENT)
    from /Users/andreag/.rvm/rubies/ruby-1.8.7-p352/lib/ruby/1.8/fileutils.rb:506:in`move'
    from /Users/andreag/.rvm/rubies/ruby-1.8.7-p352/lib/ruby/1.8/fileutils.rb:1402:in `fu_each_src_dest'
    from /Users/andreag/.rvm/rubies/ruby-1.8.7-p352/lib/ruby/1.8/fileutils.rb:1418:in`fu_each_src_dest0'
    from /Users/andreag/.rvm/rubies/ruby-1.8.7-p352/lib/ruby/1.8/fileutils.rb:1400:in `fu_each_src_dest'
    from /Users/andreag/.rvm/rubies/ruby-1.8.7-p352/lib/ruby/1.8/fileutils.rb:495:in`move'
    from /Users/andreag/.rvm/gems/ruby-1.8.7-p352@chef/gems/librarian-0.0.8/lib/librarian/chef/source/site.rb:264:in `cache_version_package!'
    from /Users/andreag/.rvm/gems/ruby-1.8.7-p352@chef/gems/librarian-0.0.8/lib/librarian/chef/source/site.rb:80:in`fetch_version_manifest!'
    from /Users/andreag/.rvm/gems/ruby-1.8.7-p352@chef/gems/librarian-0.0.8/lib/librarian/chef/source/site.rb:76:in `version_manifest'
    from /Users/andreag/.rvm/gems/ruby-1.8.7-p352@chef/gems/librarian-0.0.8/lib/librarian/chef/source/site.rb:42:in`fetch_dependencies!'
    from /Users/andreag/.rvm/gems/ruby-1.8.7-p352@chef/gems/librarian-0.0.8/lib/librarian/manifest.rb:49:in `dependencies'
    from /Users/andreag/.rvm/gems/ruby-1.8.7-p352@chef/gems/librarian-0.0.8/lib/librarian/resolver.rb:62:in`recursive_resolve'
    from /Users/andreag/.rvm/gems/ruby-1.8.7-p352@chef/gems/librarian-0.0.8/lib/librarian/resolver.rb:104:in `scope'
    from /Users/andreag/.rvm/gems/ruby-1.8.7-p352@chef/gems/librarian-0.0.8/lib/librarian/resolver.rb:59:in`recursive_resolve'
    from /Users/andreag/.rvm/gems/ruby-1.8.7-p352@chef/gems/librarian-0.0.8/lib/librarian/resolver.rb:56:in `each'
    from /Users/andreag/.rvm/gems/ruby-1.8.7-p352@chef/gems/librarian-0.0.8/lib/librarian/resolver.rb:56:in`recursive_resolve'
    from /Users/andreag/.rvm/gems/ruby-1.8.7-p352@chef/gems/librarian-0.0.8/lib/librarian/resolver.rb:104:in `scope'
    from /Users/andreag/.rvm/gems/ruby-1.8.7-p352@chef/gems/librarian-0.0.8/lib/librarian/resolver.rb:55:in`recursive_resolve'
    from /Users/andreag/.rvm/gems/ruby-1.8.7-p352@chef/gems/librarian-0.0.8/lib/librarian/resolver.rb:104:in `scope'
    from /Users/andreag/.rvm/gems/ruby-1.8.7-p352@chef/gems/librarian-0.0.8/lib/librarian/resolver.rb:38:in`recursive_resolve'
    from /Users/andreag/.rvm/gems/ruby-1.8.7-p352@chef/gems/librarian-0.0.8/lib/librarian/resolver.rb:23:in `resolve'
    from /Users/andreag/.rvm/gems/ruby-1.8.7-p352@chef/gems/librarian-0.0.8/lib/librarian/resolver.rb:129:in`resolve'
    from /Users/andreag/.rvm/gems/ruby-1.8.7-p352@chef/gems/librarian-0.0.8/lib/librarian.rb:158:in `resolve!'
    from /Users/andreag/.rvm/gems/ruby-1.8.7-p352@chef/gems/librarian-0.0.8/lib/librarian/cli.rb:74:in`update'
    from /Users/andreag/.rvm/gems/ruby-1.8.7-p352@chef/gems/thor-0.14.6/lib/thor/task.rb:22:in `send'
    from /Users/andreag/.rvm/gems/ruby-1.8.7-p352@chef/gems/thor-0.14.6/lib/thor/task.rb:22:in`run'
    from /Users/andreag/.rvm/gems/ruby-1.8.7-p352@chef/gems/thor-0.14.6/lib/thor/invocation.rb:118:in `invoke_task'
    from /Users/andreag/.rvm/gems/ruby-1.8.7-p352@chef/gems/thor-0.14.6/lib/thor.rb:263:in`dispatch'
    from /Users/andreag/.rvm/gems/ruby-1.8.7-p352@chef/gems/thor-0.14.6/lib/thor/base.rb:389:in `start'
    from /Users/andreag/.rvm/gems/ruby-1.8.7-p352@chef/gems/librarian-0.0.8/lib/librarian/cli.rb:15:in`bin!'

**Comment by yfeldblum** [comment]
Thanks for reporting this!
