### ISSUE TITLE
gitlab ref

### ISSUE THREAD

**Issue by llonchj** [applicationsonline/librarian#123]
Support for ref in a github  does NOT work for me:

```
cookbook "database",
  :github => "michaelklapper/database",
  :ref => "grant_statement"
```

but this works:

```
cookbook "database",
  :git => "https://github.com/michaelklapper/database",
  :ref => "grant_statement"
```

**Comment by yfeldblum** [comment]
With [`master`](https://github.com/applicationsonline/librarian) or with [`v0.0.25`](https://github.com/applicationsonline/librarian/tree/v0.0.25)?

**Comment by llonchj** [comment]
with 0.0.25, installed via gem install. Is the feature implemented in master?

**Comment by yfeldblum** [comment]
Correct, the feature is still in master and not yet released.

**Comment by llonchj** [comment]
Thanks for your prompt reply and looking forward for the feature to be
released.

2012/12/30 Jay Feldblum notifications@github.com
