### ISSUE TITLE
JRuby and Open3.popen3 compatibility bug

### ISSUE THREAD

**Issue by lolindrath** [applicationsonline/librarian#127]
JRuby doesn't set `$?` until after the `Open3.popen3` block has finished.
Moving the error checking logic outside fixes this problem.

See: https://github.com/applicationsonline/librarian/pull/126 for a proposed fix.

**Comment by lolindrath** [comment]
As a side note, Open3.popen3 logic seems to be weirdly implemented in both MRI 1.8 and JRuby. MRI never returns any exit code but 1.8 and also waits for the process to be finished before yielding the block (I'm not sure how you would work with interactive processes in this case). JRuby, when using the non-block format (i.e. `i,o,e = Open3.popen3("testing")`) doesn't seem to set the `$?` variable at all.

**Comment by yfeldblum** [comment]
How are you using jruby? Did you enable C extensions?

**Comment by lolindrath** [comment]
I'm using JRuby 1.6.5.1 as compiled and configured by RVM, running in 1.8 compatibility mode. `native.enabled` is on by default so I believe that means JRuby can access all gem C extensions.

**Comment by yfeldblum** [comment]
#126 has been merged. The specs pass on JRuby 1.7 in both 1.8 and 1.9 mode.
