### ISSUE TITLE
Librarian specfiles should have correct __FILE__ during evaluation

### ISSUE THREAD

**Issue by fujin** [applicationsonline/librarian#138]
A user may wish to reference files contained in the local directory, etc, and a common form for doing so is:

``` ruby
current_dir = File.dirname(__FILE__)
```

This currently yields something like
current_dir /home/aj/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/librarian-0.1.0.beta.1/lib/librarian/dsl

Cheers,

AJ

**Comment by yfeldblum** [comment]
Fixed by a04d49006b942b9c2ba74e8f0c7f4a56b500e46f.
