### ISSUE TITLE
Couldn't find home environment expanding '~'

### ISSUE THREAD

**Issue by rehevkor5** [applicationsonline/librarian#146]
Line 29 of Environment:
`@home = options.fetch(:home) { File.expand_path("~") }` relies on $HOME being set. If it's, not an error is raised saying "Couldn't find home environment expanding '~'"

Other people have encountered similar problems with other libraries. For example, https://github.com/opscode/chef/pull/624

**Comment by bradleyd** [comment]
see #147 for a potential fix.

take care.

**Comment by yfeldblum** [comment]
#147 is merged.
