### ISSUE TITLE
librarian-chef: 1.9.1/tsort.rb:152:in `block in tsort_each': topological sort failed: ["windows", "powershell"] (TSort::Cyclic)

### ISSUE THREAD

**Issue by marcellodesales** [applicationsonline/librarian#158]
I have a Cheffile with my dependencies and everything was working fine... 

mdesales@Work ~/dev/workboxes/cfp-workbox/chef (master) $ librarian-chef update
Installing apache2 (1.8.14)
Installing partial_search (1.0.6)
Installing ssh_known_hosts (1.1.0)
Installing users (1.6.0)
Installing vim (1.1.0)
Installing extend_lwrp (0.1.0)

I added more dependencies and wanted to run a fresh "librarian-chef" update again... No matter which version of ruby I use, the command fails to download all my dependencies with the error displayed in the topic... For instance, uncommenting "homesick", 'git' or java' gives the error...
# !/usr/bin/env ruby
# ^syntax detection

site 'http://community.opscode.com/api/v1'
# cookbook 'chef-client'
# cookbook 'java', '>= 1.7.0'

cookbook 'apache2', '>= 1.0.0'
# cookbook 'git', '>= 1.8.5'
# cookbook 'oh-my-zsh'

cookbook 'vim'

 #installs public git repositories for each user's dotfiles (eg .vimrc, .bashrc)
 #cookbook 'homesick'

 # The following additional cookbooks are required to support dotfiles repositories
 # requiring SSH key authentication via agent forwarding:
 cookbook 'homesick_agent', :git => 'git://github.com/dergachev/chef_homesick_agent.git'
 #cookbook 'root_ssh_agent', :git => 'git://github.com/dergachev/chef_root_ssh_agent.git'
 cookbook 'users'
 cookbook 'extend_lwrp', :git => 'git://github.com/dergachev/chef_extend_lwrp.git'
 cookbook 'ssh_known_hosts'

mdesales@Marcello-Work ~/dev/workboxes/cfp-workbox/chef (master) $ librarian-chef update
/Users/mdesales/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/1.9.1/tsort.rb:152:in `block in tsort_each': topological sort failed: ["windows", "powershell"] (TSort::Cyclic)
    from /Users/mdesales/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/1.9.1/tsort.rb:183:in`block (2 levels) in each_strongly_connected_component'
    from /Users/mdesales/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/1.9.1/tsort.rb:210:in `block (2 levels) in each_strongly_connected_component_from'
    from /Users/mdesales/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/1.9.1/tsort.rb:210:in`block (2 levels) in each_strongly_connected_component_from'
    from /Users/mdesales/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/1.9.1/tsort.rb:210:in `block (2 levels) in each_strongly_connected_component_from'
    from /Users/mdesales/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/1.9.1/tsort.rb:219:in`each_strongly_connected_component_from'
    from /Users/mdesales/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/1.9.1/tsort.rb:209:in `block in each_strongly_connected_component_from'
    from /Users/mdesales/.rvm/gems/ruby-1.9.3-p484/gems/librarian-0.1.1/lib/librarian/manifest_set.rb:11:in`each'
    from /Users/mdesales/.rvm/gems/ruby-1.9.3-p484/gems/librarian-0.1.1/lib/librarian/manifest_set.rb:11:in `tsort_each_child'
    from /Users/mdesales/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/1.9.1/tsort.rb:203:in`each_strongly_connected_component_from'
    from /Users/mdesales/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/1.9.1/tsort.rb:209:in `block in each_strongly_connected_component_from'
    from /Users/mdesales/.rvm/gems/ruby-1.9.3-p484/gems/librarian-0.1.1/lib/librarian/manifest_set.rb:11:in`each'
    from /Users/mdesales/.rvm/gems/ruby-1.9.3-p484/gems/librarian-0.1.1/lib/librarian/manifest_set.rb:11:in `tsort_each_child'
    from /Users/mdesales/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/1.9.1/tsort.rb:203:in`each_strongly_connected_component_from'
    from /Users/mdesales/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/1.9.1/tsort.rb:209:in `block in each_strongly_connected_component_from'
    from /Users/mdesales/.rvm/gems/ruby-1.9.3-p484/gems/librarian-0.1.1/lib/librarian/manifest_set.rb:11:in`each'
    from /Users/mdesales/.rvm/gems/ruby-1.9.3-p484/gems/librarian-0.1.1/lib/librarian/manifest_set.rb:11:in `tsort_each_child'
    from /Users/mdesales/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/1.9.1/tsort.rb:203:in`each_strongly_connected_component_from'
    from /Users/mdesales/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/1.9.1/tsort.rb:182:in `block in each_strongly_connected_component'
    from /Users/mdesales/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/1.9.1/tsort.rb:180:in`each_key'
    from /Users/mdesales/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/1.9.1/tsort.rb:180:in `each_strongly_connected_component'
    from /Users/mdesales/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/1.9.1/tsort.rb:148:in`tsort_each'
    from /Users/mdesales/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/1.9.1/tsort.rb:135:in `tsort'
    from /Users/mdesales/.rvm/gems/ruby-1.9.3-p484/gems/librarian-0.1.1/lib/librarian/manifest_set.rb:31:in`sort'
    from /Users/mdesales/.rvm/gems/ruby-1.9.3-p484/gems/librarian-0.1.1/lib/librarian/resolver.rb:73:in `sort'
    from /Users/mdesales/.rvm/gems/ruby-1.9.3-p484/gems/librarian-0.1.1/lib/librarian/resolver.rb:19:in`resolve'
    from /Users/mdesales/.rvm/gems/ruby-1.9.3-p484/gems/librarian-0.1.1/lib/librarian/action/resolve.rb:26:in `run'
    from /Users/mdesales/.rvm/gems/ruby-1.9.3-p484/gems/librarian-0.1.1/lib/librarian/cli.rb:169:in`resolve!'
    from /Users/mdesales/.rvm/gems/ruby-1.9.3-p484/gems/librarian-0.1.1/lib/librarian/cli.rb:113:in `update'
    from /Users/mdesales/.rvm/gems/ruby-1.9.3-p484/gems/thor-0.18.1/lib/thor/command.rb:27:in`run'
    from /Users/mdesales/.rvm/gems/ruby-1.9.3-p484/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
    from /Users/mdesales/.rvm/gems/ruby-1.9.3-p484/gems/thor-0.18.1/lib/thor.rb:363:in`dispatch'
    from /Users/mdesales/.rvm/gems/ruby-1.9.3-p484/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
    from /Users/mdesales/.rvm/gems/ruby-1.9.3-p484/gems/librarian-0.1.1/lib/librarian/cli.rb:26:in`block (2 levels) in bin!'
    from /Users/mdesales/.rvm/gems/ruby-1.9.3-p484/gems/librarian-0.1.1/lib/librarian/cli.rb:31:in `returning_status'
    from /Users/mdesales/.rvm/gems/ruby-1.9.3-p484/gems/librarian-0.1.1/lib/librarian/cli.rb:26:in`block in bin!'
    from /Users/mdesales/.rvm/gems/ruby-1.9.3-p484/gems/librarian-0.1.1/lib/librarian/cli.rb:47:in `with_environment'
    from /Users/mdesales/.rvm/gems/ruby-1.9.3-p484/gems/librarian-0.1.1/lib/librarian/cli.rb:26:in`bin!'
    from /Users/mdesales/.rvm/gems/ruby-1.9.3-p484/gems/librarian-chef-0.0.2/bin/librarian-chef:7:in `<top (required)>'
    from /Users/mdesales/.rvm/gems/ruby-1.9.3-p484/bin/librarian-chef:23:in`load'
    from /Users/mdesales/.rvm/gems/ruby-1.9.3-p484/bin/librarian-chef:23:in `<main>'
    from /Users/mdesales/.rvm/gems/ruby-1.9.3-p484/bin/ruby_executable_hooks:15:in`eval'
    from /Users/mdesales/.rvm/gems/ruby-1.9.3-p484/bin/ruby_executable_hooks:15:in `<main>'

mdesales@Marcello-Work ~/dev/workboxes/cfp-workbox/chef (master) $ rvm use 2.0.0
Using /Users/mdesales/.rvm/gems/ruby-2.0.0-p353
mdesales@Marcello-Work ~/dev/workboxes/cfp-workbox/chef (master) $ librarian-chef update
/Users/mdesales/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/tsort.rb:152:in `block in tsort_each': topological sort failed: ["windows", "powershell"] (TSort::Cyclic)
    from /Users/mdesales/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/tsort.rb:183:in`block (2 levels) in each_strongly_connected_component'
    from /Users/mdesales/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/tsort.rb:210:in `block (2 levels) in each_strongly_connected_component_from'
    from /Users/mdesales/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/tsort.rb:210:in`block (2 levels) in each_strongly_connected_component_from'
    from /Users/mdesales/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/tsort.rb:210:in `block (2 levels) in each_strongly_connected_component_from'
    from /Users/mdesales/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/tsort.rb:219:in`each_strongly_connected_component_from'
    from /Users/mdesales/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/tsort.rb:209:in `block in each_strongly_connected_component_from'
    from /Users/mdesales/.rvm/gems/ruby-2.0.0-p353/gems/librarian-0.1.1/lib/librarian/manifest_set.rb:11:in`each'
    from /Users/mdesales/.rvm/gems/ruby-2.0.0-p353/gems/librarian-0.1.1/lib/librarian/manifest_set.rb:11:in `tsort_each_child'
    from /Users/mdesales/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/tsort.rb:203:in`each_strongly_connected_component_from'
    from /Users/mdesales/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/tsort.rb:209:in `block in each_strongly_connected_component_from'
    from /Users/mdesales/.rvm/gems/ruby-2.0.0-p353/gems/librarian-0.1.1/lib/librarian/manifest_set.rb:11:in`each'
    from /Users/mdesales/.rvm/gems/ruby-2.0.0-p353/gems/librarian-0.1.1/lib/librarian/manifest_set.rb:11:in `tsort_each_child'
    from /Users/mdesales/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/tsort.rb:203:in`each_strongly_connected_component_from'
    from /Users/mdesales/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/tsort.rb:209:in `block in each_strongly_connected_component_from'
    from /Users/mdesales/.rvm/gems/ruby-2.0.0-p353/gems/librarian-0.1.1/lib/librarian/manifest_set.rb:11:in`each'
    from /Users/mdesales/.rvm/gems/ruby-2.0.0-p353/gems/librarian-0.1.1/lib/librarian/manifest_set.rb:11:in `tsort_each_child'
    from /Users/mdesales/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/tsort.rb:203:in`each_strongly_connected_component_from'
    from /Users/mdesales/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/tsort.rb:182:in `block in each_strongly_connected_component'
    from /Users/mdesales/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/tsort.rb:180:in`each_key'
    from /Users/mdesales/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/tsort.rb:180:in `each_strongly_connected_component'
    from /Users/mdesales/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/tsort.rb:148:in`tsort_each'
    from /Users/mdesales/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/tsort.rb:135:in `tsort'
    from /Users/mdesales/.rvm/gems/ruby-2.0.0-p353/gems/librarian-0.1.1/lib/librarian/manifest_set.rb:31:in`sort'
    from /Users/mdesales/.rvm/gems/ruby-2.0.0-p353/gems/librarian-0.1.1/lib/librarian/resolver.rb:73:in `sort'
    from /Users/mdesales/.rvm/gems/ruby-2.0.0-p353/gems/librarian-0.1.1/lib/librarian/resolver.rb:19:in`resolve'
    from /Users/mdesales/.rvm/gems/ruby-2.0.0-p353/gems/librarian-0.1.1/lib/librarian/action/resolve.rb:26:in `run'
    from /Users/mdesales/.rvm/gems/ruby-2.0.0-p353/gems/librarian-0.1.1/lib/librarian/cli.rb:169:in`resolve!'
    from /Users/mdesales/.rvm/gems/ruby-2.0.0-p353/gems/librarian-0.1.1/lib/librarian/cli.rb:113:in `update'
    from /Users/mdesales/.rvm/gems/ruby-2.0.0-p353/gems/thor-0.18.1/lib/thor/command.rb:27:in`run'
    from /Users/mdesales/.rvm/gems/ruby-2.0.0-p353/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
    from /Users/mdesales/.rvm/gems/ruby-2.0.0-p353/gems/thor-0.18.1/lib/thor.rb:363:in`dispatch'
    from /Users/mdesales/.rvm/gems/ruby-2.0.0-p353/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
    from /Users/mdesales/.rvm/gems/ruby-2.0.0-p353/gems/librarian-0.1.1/lib/librarian/cli.rb:26:in`block (2 levels) in bin!'
    from /Users/mdesales/.rvm/gems/ruby-2.0.0-p353/gems/librarian-0.1.1/lib/librarian/cli.rb:31:in `returning_status'
    from /Users/mdesales/.rvm/gems/ruby-2.0.0-p353/gems/librarian-0.1.1/lib/librarian/cli.rb:26:in`block in bin!'
    from /Users/mdesales/.rvm/gems/ruby-2.0.0-p353/gems/librarian-0.1.1/lib/librarian/cli.rb:47:in `with_environment'
    from /Users/mdesales/.rvm/gems/ruby-2.0.0-p353/gems/librarian-0.1.1/lib/librarian/cli.rb:26:in`bin!'
    from /Users/mdesales/.rvm/gems/ruby-2.0.0-p353/gems/librarian-chef-0.0.2/bin/librarian-chef:7:in `<top (required)>'
    from /Users/mdesales/.rvm/gems/ruby-2.0.0-p353/bin/librarian-chef:23:in`load'
    from /Users/mdesales/.rvm/gems/ruby-2.0.0-p353/bin/librarian-chef:23:in `<main>'
    from /Users/mdesales/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in`eval'
    from /Users/mdesales/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `<main>'

**Comment by yfeldblum** [comment]
Closing this issue in favor of #159, which is the source of this issue.
