### ISSUE TITLE
Travis builds are failing

### ISSUE THREAD

**Issue by justenwalker** [applicationsonline/librarian#162]
There are many [build errors](https://travis-ci.org/justenwalker/librarian/builds/16209164) in the latest master. This seems to be due to something on the Travis end. Perhaps a modification of `.travis.yml` is needed - but I'm not sure what exactly.
- `ruby-1.8.7`: can't run bundle install (due to a platform issue?)
- `rbx-18mode`: ruby rbx-d18 is not found by rvm
- `rbx-19mode`: ruby rbx-d19 is not found by rvm
- `jruby-d18`: can't run bundle install (due to a platform issue?)
- `jruby-d19`: has spec errors (Patch submitted #161)

**Comment by yfeldblum** [comment]
We are now [passing](https://travis-ci.org/applicationsonline/librarian/builds/17216013).
