### ISSUE TITLE
Is there a way to specific cookbook versions from community site?

### ISSUE THREAD

**Issue by patcon** [applicationsonline/librarian#17]
Am I crazy? I've been reading through the code trying to figure it out, but no luck. Seems that in order to this to be a true definition of an infrastructure (that we can rebuild from if ever needed), we need to be able to specify a cookbook version from the :site...

Am I missing something?

Awesome gem though, by the way! Was so pumped when I heard about this...

**Comment by yfeldblum** [comment]
You can specify a version on cookbooks:

```
site 'http://community.opscode.com/api/v1'
# An exact version
cookbook 'apache2', '0.12.2'
# A version constraint
cookbook 'apache2', '>= 1.0.0'
```

When you run `librarian-chef resolve` that will create a `Cheffile.lock` that pins the version of `apache2` and everything `apache2` depends on. The pinned versions will be consistent with whatever constraints you set in your `Cheffile`.

**Comment by patcon** [comment]
Ah... wasn't familiar with the `cookbook 'mycookbook', 'x.y.z'` format. Thanks Jay!

**Comment by patcon** [comment]
actually, figured this might be helpful for the Cheffile boilerplate, so submitting a small pull request if you want to use it :)
