### ISSUE TITLE
Bugs with certain commands when using local cookbook that also has community cookbook

### ISSUE THREAD

**Issue by patcon** [applicationsonline/librarian#19]
Originally ran into this issue when first setting up, and partially diagnosed it, but then it went away and I couldn't figure out why. This is the error I get:

http://pastebin.com/FkYRCPX5

I got it during the initial `librarian-chef install`, but then it went away for unknown reasons and now it only appears for `librarian-chef update`. Seems to involve this entry (but no other comparable entries):

```
cookbook 'newrelic',
  :path => 'cookbooks-sources'
```

It seems that newrelic is also a cookbook on the community site (but a different one), so my thought it that this is causing the issue. (The other cookbooks in `cookbooks-sources` either don't exist on community.opscode.com, or they exist, but my local version is only a slight modification, ie. the deps are likely the same)

Anyhow, I'll just use git repos in the Cheffile for now (as opposed to local refs to git submodules, which is simpler for active dev)

Thanks!

**Comment by patcon** [comment]
taking a stab at this now, but I'm a little new to ruby...

**Comment by yfeldblum** [comment]
Thanks for providing the debugging output.

The following lines stand out to me:

```
[Librarian]                                                     Checking newrelic/0.0.1 <cookbooks-sources>
[Librarian]                                                       Scheduling  (>= 0.0.0) <http://community.opscode.com/api/v1>
...
[Librarian]                                                             Resolving  (>= 0.0.0) <http://community.opscode.com/api/v1>
[Librarian]                                                               No known prior constraints
/Library/Ruby/Gems/1.8/gems/librarian-0.0.12/lib/librarian/chef/source/site.rb:68:in `manifests': undefined method `map' for nil:NilClass (NoMethodError)
```

Do you have a line like `depends ""` in `cookbooks-sources/newrelic/metadata.rb`?

**Comment by patcon** [comment]
motherfrack. you're right. was in the metadata.json

Oy. Sorry Jay. Hopefully this didn't take as much of your time as it did of mine...!

Thanks again. You're a hero

**Comment by yfeldblum** [comment]
#20, #21.

**Comment by patcon** [comment]
I like your style, sir
