### ISSUE TITLE
Should readme indicate that tmp should be install .gitignore as well?

### ISSUE THREAD

**Issue by patcon** [applicationsonline/librarian#22]
I've added it, but I'm unsure whether it's best-practice. Clarification would be helpful in the docs.

**Comment by yfeldblum** [comment]
Yes, unless there's something else in your repo that expects `tmp/` to exist, you can gitignore it.

**Comment by yfeldblum** [comment]
Want to submit a patch to the readme?

**Comment by patcon** [comment]
haha dealio

**Comment by yfeldblum** [comment]
Fixed by #23.
