### ISSUE TITLE
Greasemonkey script to make code review simpler

### ISSUE THREAD

**Issue by patcon** [applicationsonline/librarian#24]
Ref: heavywater/pennyworth#6

Comment over here had a point -- code review is awkward when the code is spread around and not conveniently linked. Never written a greasemonkey script, but it seems something that would be worth doing. I'll see if I can find some time and pass it along when I get it working.

For now, I'll just link to the opscode community site (As there's a link to the code there), but perhaps I could get more complex and use their api later.

**Comment by yfeldblum** [comment]
If a Greasemonkey script were written, it would have to be a separate project. It's strictly beyond the scope of Librarian.

I likely wouldn't be the one to write such a project. But if one were written, I wouldn't be averse to including a link to it in the Librarian readme.

**Comment by patcon** [comment]
Totally right -- def doesn't belong in the repo. It's beyond the scope, but I'd argue that it might be pretty important if it's addressing what's likely a big reason people avoid using the tool. Anyhow, haven't had time, but will keep ya posted

**Comment by patcon** [comment]
Would you mind leaving this open in case anyone else wants to take a stab at it? I realize it's unorthodox, but if these are queues for the project as a whole, it's not too much of a stretch. No hard feelings if it's not your style :)

**Comment by yfeldblum** [comment]
It's a completely separate project, one that I don't plan to do myself. Thank you for the suggestion, though.

I am averse to keeping project-specific issues open, when there is no intention of resolving them within the project. I want to keep the GitHub issues page specific to issues, rather than widening it to become a forum or mailing list for a general surrounding discussion.

**Comment by patcon** [comment]
Having started with tending some issue queues of my own, I totally agree. Thanks for humoring me before at the time!
