### ISSUE TITLE
Add option for :path to strip .git dir (when pulling in submodule)

### ISSUE THREAD

**Issue by patcon** [applicationsonline/librarian#25]
heavywater/pennyworth#14

The above issue made me realize that there might be a deficiency to removing the `cookbooks` dir from `.gitignore`, in that if there are submodules in the `cookbooks-sources` directory, their `.git` folders are pulled in, and this gets messy. Would some sort of per-cookbook strip option be possible?

```
cookbook 'mycookbook',
  :path => 'cookbooks-sources',
  :exclude => [ ".git" ]
```

Thoughts?

**Comment by patcon** [comment]
Marked for myself: https://github.com/applicationsonline/librarian/blob/master/lib/librarian/chef/source/local/manifest.rb#L60

Any thoughts on my using this code as the basis to add a helper function?
http://iamneato.com/2009/07/28/copy-folders-recursively

**Comment by patcon** [comment]
Hm. These have exclude logic for me to check over as well:
http://svn.rails-engines.org/engines/trunk/Rakefile
http://stackoverflow.com/a/711315

**Comment by yfeldblum** [comment]
Using both Librarian and Git-submodules is like killing one bird with two stones. They are, from 30,000 feet, there for the same reason. You usually won't need both of them in the same project.

In this case, just use Librarian instead of Git submodules.

```
cookbook 'mycookbook', :git => 'https://github.com/user/project'

$ librarian-chef install
```

Later, to update the version of the cookbook pulled down into your repository:

```
$ librarian-chef update mycookbook
$ librarian-chef install
```

The `:path => "cookbooks-sources"` option is really there e.g. in case you actually want to vendor a specific cookbook into your repository and use that as the version that Librarian sees (without having to vendor all the cookbooks in `cookbooks/`).

**Comment by patcon** [comment]
Hmm.. ok, that's a good point. Didn't quite realize that I could comment out the `:ref` property and still have librarian follow HEAD while still pinning with a commit hash :)

I suppose the sole reason to use submodules and :path though would be to make the code more browsable on github, which @fujin's observations have made me realize is pretty important -- I want everyone in our organization to be able to easily navigate and poke around if with minimal resistance.

Also, that same request (for an exclude param) could apply to the git cookbook type, as the `.git` dir seems to remain in their as well. Of course, I guess adding `cookbooks/*/.git` to `.gitignore` should also do the trick, I guess...!

I still think submodules have a use, but given the `.gitignore` angle that I hadn't recognized before, I'm probably fine to close this out :)

**Comment by patcon** [comment]
Just writing a cookbook for freight now, and coming across a good reason to use submodules and librarian-chef together. Thought I'd explain:

Whenever I'm building a new cookbook, I start a vagrant env repo called `cookbookname-cooking`. I don't push this publicly, but I immediately push a `chef-cookbookname`  skeleton repo public. I then pull that into the vagrant repo and begin dev. If it were to add this as a simple git ref in the `Cheffile`, then --say-- I get writing and realize I need to add a `require_receipe "apache2"` or whatever. So I add this line, and then go to add apache2 cookbook to the Cheffile.

Now if I understand correctly, I'd need to push my changes even if I'm not ready, or `librarian-chef update` and `librarian-chef install` will overwrite my work. This is a bit inconvenient. If I have this in-progress `chef-cookbookname` repo in a submodule that's pulled in from `cookbooks-sources`, then I can run `librarian-chef` commands as I develop, and librarian doesn't get in my way and force me to commit before I'm ready to.

Is this an example of a reason to use submodules, or am I missing a feature of librarian? Hopefully this use-case is helpful for you too :)

**Comment by yfeldblum** [comment]
Librarian automates resolving and fetching a consistent set of finished, versioned third-party cookbooks. But sometimes, strict automation gets in the way of hacking.

I don't think you're missing a feature of Librarian. Actually, for me, using Librarian to resolve and fetch specific cookbooks gets in the way of me hacking on them. It's not really meant for that.

It's really for pulling in the 50 or so finished third-party cookbooks that you're using, not the 1 or 2 cookbooks you're actively working on. So, for me, I would just tend not to use Librarian for cookbooks I'm actively working on.

For this case, I might just clone `chef-cookbookname` into `cookbookname-cooking/cookbooks-in-progress` (not even a submodule necessarily, just a clone) and start hacking. I might stick `apache2` into the Cheffile, but not `cookbookname`. I would add both cookbooks directories to the Vagrantfile, and add `cookbookname` to the run-list (make sure its `metadata.rb` declares `depends "apache2"`), but there's no need for Librarian to get involved with that.

**Comment by patcon** [comment]
Hmm... good points :)

Seems `cookbooks-sources` probably isn't necessary here, but I still think I'd keep things as submodules in `cookboks-in-progress`, since I think I'm going to try to get in the habit of putting my `cookbookname-cooking` vagrant repos into github, to make it simpler for people to get started hacking on anything I'm doing (and so everyone is debugging and hacking with a consistent set of cookbooks?)

Thanks Jay! :)

**Comment by yfeldblum** [comment]
Just thinking out loud about cookbook repo structure.

So if your repository looked like:

```
patcon/mycookbookname/
  cookbook/
    attributes/
    recipes/
    metadata.rb
  spec/
  vagrant/
    cookbooks/
    Cheffile
    Vagrantfile
```

Then the `vagrant/Cheffile` in that repository can declare:

```
cookbook "mycookbookname",
  :path => "../cookbook"
```

While everyone else's `Cheffile` can declare:

```
cookbook "mycookbookname",
  :git => "https://github.com/patcon/mycookbookname",
  :ref => "1.3-stable",
  :path => "cookbook"
```

I.e., you just have your actual cookbook in one subdirectory and the testing stuff in another.

**Comment by patcon** [comment]
I LIKE IT.
Maybe I'm crazy, but I get immense satisfaction out of ironing out stuff like this (for my own purposes) :)
