### ISSUE TITLE
librarian throws errors when using "wrong" array structure

### ISSUE THREAD

**Issue by patcon** [applicationsonline/librarian#28]
Sorry if I'm just kinda making up technical words here, but I don't know the specific term.

Basically, I did this in one metadata.rb:

```
%{
  apache2
  apt
  gpg
}.each do |cookbook|
  depends cookbook
end
```

It actually worked for awhile, but threw random errors. Also noticed that it created a folder deep down in /tmp called `\n`.

In retrospect, I should've been using `%w{ }`, but it couldn't hurt to deal with it so it doesn't discourage someone else :)

Come to think of it, I think I picked up that format from fujin while I was browsing the pennyworth code, so it might explain my weird sporadic errors over there too

Cheers!

**Comment by yfeldblum** [comment]
#29.

**Comment by yfeldblum** [comment]
Not that my cookbook metadata style preference is relevant to Librarian, but I actually don't like listing dependencies that way. I would typically write the dependency list as:

```
depends "apache2"
depends "apt"
depends "gpg"
```

**Comment by patcon** [comment]
haha Now that you've written it out, it does seem rather silly to have used a control structure just because I could :P

NEW HABIT SUCCESSFULLY FORMED. Thank you, sir
