### ISSUE TITLE
Use FakeFS in unit tests

### ISSUE THREAD

**Issue by yfeldblum** [applicationsonline/librarian#30]

**Comment by hedgehog** [comment]
Are you working on this?

I have some spec_helper code that would be a neat setup of the scaffolding.  It'd then remain to tag the examples (`tag: :fakefs`) and set up required files - which is example specific.

Thoughts?

**Comment by yfeldblum** [comment]
I am not currently working on it.

It seems like it would be a good idea in general to fake the filesystem in unit tests, but I don't actually know if that's the case. I haven't looked into it enough and I haven't actually tried it out.

If this is something you value, go for it.

**Comment by hedgehog** [comment]
In my experience it has definitely proved valuable - leading to simpler specs, since you test directly rather than for side-effects because you can't hit the file system.

**Comment by yfeldblum** [comment]
As of now, the only unit test that needs this is the unit test for `Librarian::Config::Database`, and [it has it](https://github.com/applicationsonline/librarian/blob/55a02a0f6bd0f4369545287bf4c22225ca744791/spec/unit/config/database_spec.rb).

There are other tests that access the filesystem, specifically the chef git- and site-source specs, but these are marked as functional tests rather than unit tests. The unit tests are in `spec/unit/` and the functional tests are in `spec/functional/`, so they are clearly demarcated.
