### ISSUE TITLE
vagrant 0.9.3 no longer compatible with librarian when bundled

### ISSUE THREAD

**Issue by patcon** [applicationsonline/librarian#35]
Ran into this with trying to bundle vagrant 0.9.3 and librarian 0.0.12.

Seems that chef 0.10.8 release is still dependant on net-ssh 2.1.3, while vagrant is set to 2.2.2. Just a heads up that you might want to include a `Gemfile` to offer an example resolution until the next version of chef comes out (despite it being a vagrant dilemma :)

```
gem "vagrant",   "= 0.9.3"
gem "librarian", "= 0.0.12"
# net-ssh dependency bumped to 2.2.2 (to match librarian)
gem "chef",
  :git => "https://github.com/opscode/chef.git",
  :ref => "ba4d58f4223"
```

**Comment by yfeldblum** [comment]
Thanks for the tip.

Neither librarian nor librarian-chef has a direct dependency on either vagrant or net-ssh. A gem-dependency conflict between chef (which librarian-chef depends on) and vagrant (which librarian/librarian-chef does not depend on) regarding net-ssh (which librarian/librarian-chef does not depend directly on and does not use in any way) is really not librarian's job to fix.

While there are many options available for gems management, including manual management of shared system gems, rvm-gemsets, bundler, isolate, etc., I would like to keep librarian's documentation limited to documenting librarian - including how to install librarian, but not including how to fix problems that haven't got anything directly to do with librarian.

However, this topic would make for a good blog post titled "On Using Chef, Vagrant, and Librarian with Bundler."

**Comment by patcon** [comment]
haha thanks Jay. You're 100% right. I think the issue would've been more appropriately addressed to other users rather than yourself, as a heads up :)
