### ISSUE TITLE
librarian-chef update does not pick up changes from remote git repositories

### ISSUE THREAD

**Issue by databus23** [applicationsonline/librarian#36]
I'm having trouble updating cookbooks from remote git repositories with librarian-chef update.

I have a cookbook included in my Cheffile like this:

cookbook 'system',     :git => 'git://mygitserver.example.com/system.git', :ref=>'master'

It looks to me that after the initial caching(cloning) of the remote repository in tmp/librarian/cache/source/git/... new commits in the master branch don't get pulled at all.

The solution for me is to issue a librarian-chef clean to flush the cache. After that a librarian-chef update pulls in the latest changes from the upstream repository.

I'm I missing something or is this a bug in librarian?

**Comment by yfeldblum** [comment]
If you've got some real-world cases, mind testing the most recent master?

**Comment by databus23** [comment]
May local test cases I used for testing so far work perfectly now.
Thanks a lot! Looks to me its working now. That's great

Could you release a new librarian gem version, please!

**Comment by yfeldblum** [comment]
Released as v0.0.13.
