### ISSUE TITLE
Windows Support in lib/librarian/chef/source/site.rb

### ISSUE THREAD

**Issue by djberg96** [applicationsonline/librarian#50]
You're using a Process.waitpid2 + fork combo in site.rb. This isn't really necessary, and it won't work on Windows. Instead, I recommend using the system() method since it works on Windows and it blocks by defualt. Alternatively, you could use open3 if you really need more detailed information on failure. For 1.8 you would need the win32-open3 gem.

I would also suggest replacing a hard coded 'tar' command with an actual tar interface, e.g. zlib, minitar, etc, since you cannot guarantee the presence of tar on Windows (or any *nix platform really).

**Comment by yfeldblum** [comment]
[lib/librarian/chef/source/site.rb](https://github.com/applicationsonline/librarian/blob/v0.0.14/lib/librarian/chef/source/site.rb#L187-194)

**Comment by yfeldblum** [comment]
Fixed in d936d6d61efbef57c2c67cef58326cb0fb3f905f.

**Comment by yfeldblum** [comment]
Any other problematic code?

**Comment by djberg96** [comment]
Not that I saw offhand. Although, the test suite could use some love regardless of platform to make sure. I saw 26 failures on OSX even.

**Comment by yfeldblum** [comment]
No doubt.

**Comment by yfeldblum** [comment]
I checked on OSX and saw no errors.

Did you make sure to run the specs in a bundled environment?

```
bundle
bundle exec rspec spec
bundle exec cucumber
```

**Comment by djberg96** [comment]
I don't think I did that. Perhaps "rake spec" should do that automatically. Or is there a good reason not to do that?

**Comment by yfeldblum** [comment]
There is a good reason. It inverts the normal loading order. The bundle includes a version of Rake, but you might invoke a different version of Rake.

**Comment by yfeldblum** [comment]
Documented in a3bcb1dcb35c0a97c48ac85be347d76c143807ce.

**Comment by yfeldblum** [comment]
@djberg96 thank you for the tips!
