### ISSUE TITLE
cookbooks with underscore in the name fail to tsort

### ISSUE THREAD

**Issue by hh** [applicationsonline/librarian#51]
https://gist.github.com/2354413

tsort.rb:152:in `block in tsort_each': topological sort failed: ["windows", "chef_handler", "webpi"](TSort::Cyclic)

The same code, using a cookbook without an underscore succeeds.

**Comment by yfeldblum** [comment]
There is actual a cycle in the dependencies.
- [`windows`](https://github.com/opscode-cookbooks/windows/blob/master/metadata.rb) depends on `chef_handler`.
- [`webpi`](https://github.com/opscode/cookbooks/blob/9948e1d00148766b7f2cc5d8690bd0b40382a314/webpi/metadata.rb) depends on `windows`.
- [`chef_handler`](https://github.com/hh/cookbooks/blob/master/iis/metadata.rb) depends on `windows` and `webpi`.

It looks like the cookbook declared as `chef_handler` in your Cheffile should actually be named `iis`.

**Comment by hh** [comment]
I should have caught that 8)
