### ISSUE TITLE
Running install causes errror

### ISSUE THREAD

**Issue by apeshimam** [applicationsonline/librarian#56]
Verbose output: 
ip-172-16-5-158:chef-repo apeshimam$ librarian-chef install --verbose
[Librarian] Pre-Cached Sources:
[Librarian] Post-Cached Sources:
[Librarian]   [:site, "http://community.opscode.com/api/v1", {}]
[Librarian]   [:git, "https://github.com/fnichol/chef-jenkins", {:ref=>"v0.5"}]
[Librarian]   [:git, "https://github.com/fnichol/chef-rvm", {:ref=>"v0.8.6"}]
[Librarian]   [:git, "git@github.com:CXInc/chef-cxapi.git", {}]
[Librarian]   [:git, "git@github.com:CXInc/chef-cxdb.git", {}]
[Librarian]   [:git, "git@github.com:CXInc/chef-cxror.git", {}]
[Librarian]   [:git, "git@github.com:CXInc/chef-cxvpn.git", {}]
[Librarian]   [:git, "git@github.com:CXInc/chef-haproxy.git", {}]
[Librarian]   [:git, "git@github.com:CXInc/chef-hostname.git", {}]
[Librarian]   [:git, "git@github.com:CXInc/chef-munin.git", {}]
[Librarian]   [:git, "git@github.com:CXInc/chef-nagios.git", {}]
[Librarian]   [:git, "git@github.com:CXInc/chef-percona-install.git", {}]
[Librarian]   [:git, "git@github.com:CXInc/chef-php-fpm.git", {}]
[Librarian]   [:git, "git@github.com:CXInc/chef-rundeck.git", {}]
[Librarian]   [:git, "git@github.com:CXInc/chef-ssh_known_hosts.git", {}]
[Librarian]   [:git, "git@github.com:CXInc/chef-s3cmd_logs.git", {}]
[Librarian]   [:git, "git@github.com:CXInc/chef-stud.git", {}]
[Librarian]   [:git, "git@github.com:CXInc/chef-users.git", {}]
[Librarian]   [:git, "git@github.com:CXInc/chef-wordpress.git", {}]
[Librarian] Scheduling apache2 (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling application (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling apt (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling aws (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling build-essential (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling couchdb (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling cron (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling chef-client (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling chef_handler (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling chef-server (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling database (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling elasticsearch (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling erlang (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling git (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling graylog2 (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling java (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling logrotate (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling logstash (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling memcached (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling mysql (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling nginx (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling ntp (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling ohai (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling openssh (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling openssl (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling openvpn (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling perl (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling php (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling postfix (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling python (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling rabbitmq (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling rabbitmq_chef (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling route53 (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling rsync (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling rsyslog (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling runit (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling sensu (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling solr (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling sudo (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling sysctl (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling tmux (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling ucspi-tcp (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling varnish (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling vim (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling xfs (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling xml (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling yum (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling zlib (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling zookeeper (>= 0) http://community.opscode.com/api/v1
[Librarian] Scheduling jenkins (>= 0) https://github.com/fnichol/chef-jenkins#v0.5
[Librarian] Scheduling rvm (>= 0) https://github.com/fnichol/chef-rvm#v0.8.6
[Librarian] Scheduling chef-cxapi (>= 0) <git@github.com:CXInc/chef-cxapi.git#master>
[Librarian] Scheduling cxdb (>= 0) <git@github.com:CXInc/chef-cxdb.git#master>
[Librarian] Scheduling cxror (>= 0) <git@github.com:CXInc/chef-cxror.git#master>
[Librarian] Scheduling cxvpn (>= 0) <git@github.com:CXInc/chef-cxvpn.git#master>
[Librarian] Scheduling haproxy (>= 0) <git@github.com:CXInc/chef-haproxy.git#master>
[Librarian] Scheduling hostname (>= 0) <git@github.com:CXInc/chef-hostname.git#master>
[Librarian] Scheduling munin (>= 0) <git@github.com:CXInc/chef-munin.git#master>
[Librarian] Scheduling nagios (>= 0) <git@github.com:CXInc/chef-nagios.git#master>
[Librarian] Scheduling percona-install (>= 0) <git@github.com:CXInc/chef-percona-install.git#master>
[Librarian] Scheduling php-fpm (>= 0) <git@github.com:CXInc/chef-php-fpm.git#master>
[Librarian] Scheduling rundeck (>= 0) <git@github.com:CXInc/chef-rundeck.git#master>
[Librarian] Scheduling ssh_known_hosts (>= 0) <git@github.com:CXInc/chef-ssh_known_hosts.git#master>
[Librarian] Scheduling s3cmd_logs (>= 0) <git@github.com:CXInc/chef-s3cmd_logs.git#master>
[Librarian] Scheduling stud (>= 0) <git@github.com:CXInc/chef-stud.git#master>
[Librarian] Scheduling users (>= 0) <git@github.com:CXInc/chef-users.git#master>
[Librarian] Scheduling wordpress (>= 0) <git@github.com:CXInc/chef-wordpress.git#master>
[Librarian] Resolving apache2 (>= 0) http://community.opscode.com/api/v1
[Librarian]   No known prior constraints
[Librarian] Caching http://community.opscode.com/api/v1/cookbooks/apache2
[Librarian]   Checking manifests
[Librarian]     Checking apache2/1.1.6 http://community.opscode.com/api/v1
[Librarian]       Resolving application (>= 0) http://community.opscode.com/api/v1
[Librarian]         No known prior constraints
/Users/apeshimam/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/pathname.rb:776:in `read': No such file or directory - /Users/apeshimam/chef-repo/tmp/librarian/cache/source/chef/site/877777683730772c36b1e6a3fc3aa2c3/application/metadata.json (Errno::ENOENT)
    from /Users/apeshimam/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/pathname.rb:776:in`read'
    from /Users/apeshimam/.rvm/gems/ruby-1.9.3-rc1/gems/librarian-0.0.16/lib/librarian/chef/source/site.rb:74:in `manifests'
    from /Users/apeshimam/.rvm/gems/ruby-1.9.3-rc1/gems/librarian-0.0.16/lib/librarian/dependency.rb:64:in`cache_manifests!'
    from /Users/apeshimam/.rvm/gems/ruby-1.9.3-rc1/gems/librarian-0.0.16/lib/librarian/dependency.rb:59:in `manifests'
    from /Users/apeshimam/.rvm/gems/ruby-1.9.3-rc1/gems/librarian-0.0.16/lib/librarian/resolver/implementation.rb:49:in`block in recursive_resolve'
    from /Users/apeshimam/.rvm/gems/ruby-1.9.3-rc1/gems/librarian-0.0.16/lib/librarian/resolver/implementation.rb:102:in `scope'
    from /Users/apeshimam/.rvm/gems/ruby-1.9.3-rc1/gems/librarian-0.0.16/lib/librarian/resolver/implementation.rb:36:in`recursive_resolve'
    from /Users/apeshimam/.rvm/gems/ruby-1.9.3-rc1/gems/librarian-0.0.16/lib/librarian/resolver/implementation.rb:70:in `block (4 levels) in recursive_resolve'
    from /Users/apeshimam/.rvm/gems/ruby-1.9.3-rc1/gems/librarian-0.0.16/lib/librarian/resolver/implementation.rb:102:in`scope'
    from /Users/apeshimam/.rvm/gems/ruby-1.9.3-rc1/gems/librarian-0.0.16/lib/librarian/resolver/implementation.rb:57:in `block (3 levels) in recursive_resolve'
    from /Users/apeshimam/.rvm/gems/ruby-1.9.3-rc1/gems/librarian-0.0.16/lib/librarian/resolver/implementation.rb:54:in`each'
    from /Users/apeshimam/.rvm/gems/ruby-1.9.3-rc1/gems/librarian-0.0.16/lib/librarian/resolver/implementation.rb:54:in `block (2 levels) in recursive_resolve'
    from /Users/apeshimam/.rvm/gems/ruby-1.9.3-rc1/gems/librarian-0.0.16/lib/librarian/resolver/implementation.rb:102:in`scope'
    from /Users/apeshimam/.rvm/gems/ruby-1.9.3-rc1/gems/librarian-0.0.16/lib/librarian/resolver/implementation.rb:53:in `block in recursive_resolve'
    from /Users/apeshimam/.rvm/gems/ruby-1.9.3-rc1/gems/librarian-0.0.16/lib/librarian/resolver/implementation.rb:102:in`scope'
    from /Users/apeshimam/.rvm/gems/ruby-1.9.3-rc1/gems/librarian-0.0.16/lib/librarian/resolver/implementation.rb:36:in `recursive_resolve'
    from /Users/apeshimam/.rvm/gems/ruby-1.9.3-rc1/gems/librarian-0.0.16/lib/librarian/resolver/implementation.rb:21:in`resolve'
    from /Users/apeshimam/.rvm/gems/ruby-1.9.3-rc1/gems/librarian-0.0.16/lib/librarian/resolver.rb:18:in `resolve'
    from /Users/apeshimam/.rvm/gems/ruby-1.9.3-rc1/gems/librarian-0.0.16/lib/librarian/action/resolve.rb:25:in`run'
    from /Users/apeshimam/.rvm/gems/ruby-1.9.3-rc1/gems/librarian-0.0.16/lib/librarian/cli.rb:108:in `resolve!'
    from /Users/apeshimam/.rvm/gems/ruby-1.9.3-rc1/gems/librarian-0.0.16/lib/librarian/cli.rb:67:in`install'
    from /Users/apeshimam/.rvm/gems/ruby-1.9.3-rc1/gems/thor-0.14.6/lib/thor/task.rb:22:in `run'
    from /Users/apeshimam/.rvm/gems/ruby-1.9.3-rc1/gems/thor-0.14.6/lib/thor/invocation.rb:118:in`invoke_task'
    from /Users/apeshimam/.rvm/gems/ruby-1.9.3-rc1/gems/thor-0.14.6/lib/thor.rb:263:in `dispatch'
    from /Users/apeshimam/.rvm/gems/ruby-1.9.3-rc1/gems/thor-0.14.6/lib/thor/base.rb:389:in`start'
    from /Users/apeshimam/.rvm/gems/ruby-1.9.3-rc1/gems/librarian-0.0.16/lib/librarian/cli.rb:27:in `bin!'
    from /Users/apeshimam/.rvm/gems/ruby-1.9.3-rc1/gems/librarian-0.0.16/bin/librarian-chef:7:in`<top (required)>'
    from /Users/apeshimam/.rvm/gems/ruby-1.9.2-p290/bin/librarian-chef:19:in `load'
    from /Users/apeshimam/.rvm/gems/ruby-1.9.2-p290/bin/librarian-chef:19:in`<main>'

Cheffile:
# !/usr/bin/env ruby
# ^syntax detection

site 'http://community.opscode.com/api/v1'
#100% upstream

cookbook 'apache2'
cookbook 'application'
cookbook 'apt'
cookbook 'aws'
cookbook 'build-essential'
cookbook 'couchdb'
cookbook 'cron'
cookbook 'chef-client'
cookbook 'chef_handler'
cookbook 'chef-server'
cookbook 'database'
cookbook 'elasticsearch'
cookbook 'erlang'
cookbook 'git'
cookbook 'graylog2'
cookbook 'java'
cookbook 'logrotate'
cookbook 'logstash'
cookbook 'memcached'
cookbook 'mysql'
cookbook 'nginx'
cookbook 'ntp'
cookbook 'ohai'
cookbook 'openssh'
cookbook 'openssl'
cookbook 'openvpn'
cookbook 'perl'
cookbook 'php'
cookbook 'postfix'
cookbook 'python'
cookbook 'rabbitmq'
cookbook 'rabbitmq_chef'
cookbook 'route53'
cookbook 'rsync'
cookbook 'rsyslog'
cookbook 'runit'
cookbook 'sensu'
cookbook 'solr'
cookbook 'sudo'
cookbook 'sysctl'
cookbook 'tmux'
cookbook 'ucspi-tcp'
cookbook 'varnish'
cookbook 'vim'
cookbook 'xfs'
cookbook 'xml'
cookbook 'yum'
cookbook 'zlib'
cookbook 'zookeeper'
# 3rd party

cookbook 'jenkins',
  :git => 'https://github.com/fnichol/chef-jenkins',
  :ref => 'v0.5'
cookbook 'rvm',
  :git => 'https://github.com/fnichol/chef-rvm',
  :ref => 'v0.8.6'
# CX Maintained

cookbook 'chef-cxapi',
  :git => 'git@github.com:CXInc/chef-cxapi.git'
cookbook 'cxdb',
  :git => 'git@github.com:CXInc/chef-cxdb.git'
cookbook 'cxror',
  :git => 'git@github.com:CXInc/chef-cxror.git'
cookbook 'cxvpn',
  :git => 'git@github.com:CXInc/chef-cxvpn.git'
cookbook 'haproxy',
  :git => 'git@github.com:CXInc/chef-haproxy.git'
cookbook 'hostname',
  :git => 'git@github.com:CXInc/chef-hostname.git'
cookbook 'munin',
  :git => 'git@github.com:CXInc/chef-munin.git'
cookbook 'nagios',
  :git => 'git@github.com:CXInc/chef-nagios.git'
cookbook 'percona-install',
  :git => 'git@github.com:CXInc/chef-percona-install.git'
cookbook 'php-fpm',
  :git => 'git@github.com:CXInc/chef-php-fpm.git'
cookbook 'rundeck',
  :git => 'git@github.com:CXInc/chef-rundeck.git'
cookbook 'ssh_known_hosts',
  :git => 'git@github.com:CXInc/chef-ssh_known_hosts.git'
cookbook 's3cmd_logs',
  :git => 'git@github.com:CXInc/chef-s3cmd_logs.git'
cookbook 'stud',
  :git => 'git@github.com:CXInc/chef-stud.git'
cookbook 'users',
  :git => 'git@github.com:CXInc/chef-users.git'
cookbook 'wordpress',
  :git => 'git@github.com:CXInc/chef-wordpress.git'

Cheffile.lock:

ip-172-16-5-158:chef-repo apeshimam$ cat Cheffile.lock 
SITE
  remote: http://community.opscode.com/api/v1
  specs:
    apache2 (1.1.4)
    application (0.99.14)
      apache2 (>= 0.0.0)
      gunicorn (>= 0.0.0)
      passenger_apache2 (>= 0.0.0)
      php (>= 0.0.0)
      python (>= 1.0.6)
      runit (>= 0.0.0)
      tomcat (>= 0.0.0)
      unicorn (>= 0.0.0)
    apt (1.4.0)
    aws (0.99.1)
    bluepill (1.0.4)
    build-essential (1.0.0)
    capistrano (0.7.0)
    chef-client (1.1.2)
    chef-server (0.99.12)
      apache2 (>= 0.0.0)
      bluepill (>= 0.0.0)
      couchdb (>= 0.0.0)
      daemontools (>= 0.0.0)
      gecode (>= 0.0.0)
      java (>= 0.0.0)
      nginx (>= 0.0.0)
      openssl (>= 0.0.0)
      runit (>= 0.0.0)
      xml (>= 0.0.0)
      zlib (>= 0.0.0)
    chef_handler (1.0.6)
    couchdb (1.0.0)
      erlang (>= 0.0.0)
    cron (1.0.0)
    daemontools (0.9.0)
      build-essential (>= 0)
      ucspi-tcp (>= 0)
    database (1.1.4)
      aws (>= 0.0.0)
      mysql (>= 1.2.0)
      postgresql (>= 0.0.0)
      xfs (>= 0.0.0)
    elasticsearch (0.1.0)
      bluepill (>= 0)
      java (>= 0)
    erlang (1.0.0)
      yum (>= 0.5.0)
    gecode (1.2.0)
      apt (>= 0.0.0)
      build-essential (>= 0.0.0)
    git (0.10.0)
      runit (>= 0.0.0)
      yum (>= 0.0.0)
    graylog2 (0.0.5)
      apache2 (>= 0.0.0)
      apt (>= 0.0.0)
    gunicorn (1.0.0)
      python (>= 0)
    install_from (3.0.4)
    iptables (0.10.0)
    java (1.4.2)
    logrotate (0.8.2)
    logstash (0.0.1)
      java (>= 0.0.0)
      runit (>= 0.0.0)
    memcached (1.0.2)
      runit (>= 0.0.0)
    metachef (3.0.4)
    mysql (1.2.4)
      openssl (>= 0.0.0)
    nginx (0.100.2)
      bluepill (>= 0.0.0)
      build-essential (>= 0.0.0)
      runit (>= 0.0.0)
    ntp (1.1.6)
    ohai (1.0.2)
    openssh (0.8.0)
    openssl (1.0.0)
    openvpn (0.99.2)
    passenger_apache2 (0.99.4)
      apache2 (>= 1.0.4)
      build-essential (>= 0.0.0)
    perl (0.10.0)
    php (1.0.2)
      build-essential (>= 0.0.0)
      mysql (>= 0.0.0)
      xml (>= 0.0.0)
    postfix (0.8.4)
    postgresql (0.99.4)
      openssl (>= 0.0.0)
    python (1.0.6)
      build-essential (>= 0.0.0)
    rabbitmq (1.4.0)
      apt (>= 1.1)
      erlang (>= 0.9)
      yum (>= 0.5.0)
    rabbitmq_chef (0.10.4)
      erlang (>= 0)
    redis (3.0.4)
      install_from (>= 0.0.0)
      metachef (>= 0.0.0)
      runit (>= 0.0.0)
    route53 (0.2.0)
    rsync (0.7.0)
    rsyslog (1.0.0)
      cron (>= 0.0.0)
    runit (0.15.0)
    sensu (0.0.7)
      apt (>= 0.0.0)
      git (>= 0.0.0)
      rabbitmq (>= 0.0.0)
      redis (>= 0.0.0)
    solr (0.8.1)
      capistrano (>= 0)
      java (>= 0)
      runit (>= 0)
    sudo (1.0.2)
    sysctl (0.1.0)
    tmux (1.0.0)
    tomcat (0.10.4)
      java (>= 0.0.0)
    ucspi-tcp (1.0.0)
      build-essential (>= 0)
    unicorn (1.0.0)
    varnish (0.7.0)
    vim (1.0.2)
    xfs (1.0.0)
    xml (1.0.2)
    yum (0.5.2)
    zlib (1.0.0)
    zookeeper (0.1.0)
      java (>= 0)
      runit (>= 0)

GIT
  remote: git@github.com:CXInc/chef-cxapi.git
  ref: master
  sha: c7615dc8e5327011d28f6b8564565040719f89f1
  specs:
    chef-cxapi (0.0.25)
      java (>= 1.4.2)
      runit (>= 0.0.0)

GIT
  remote: git@github.com:CXInc/chef-cxdb.git
  ref: master
  sha: c3a290ccfba7d9c10b23dc46868e6c4dc48f57b4
  specs:
    cxdb (0.0.1)

GIT
  remote: git@github.com:CXInc/chef-cxror.git
  ref: master
  sha: 4b2f0cee04663bdd8aa7fd28e0db13552039a175
  specs:
    cxror (0.0.1)
      git (>= 0.0.0)
      nginx (>= 0.0.0)
      rvm (>= 0.0.0)

GIT
  remote: git@github.com:CXInc/chef-cxvpn.git
  ref: master
  sha: 201fe9b2a6c3fd5027151ed68cdc16d799099803
  specs:
    cxvpn (0.0.1)

GIT
  remote: git@github.com:CXInc/chef-haproxy.git
  ref: master
  sha: 1973557fadf36aa6be5668ba5db81e903a378e2e
  specs:
    haproxy (1.0.58)
      build-essential (>= 0.0.0)
      git (>= 0.0.0)
      rsyslog (>= 0.0.0)
      runit (>= 0.0.0)

GIT
  remote: git@github.com:CXInc/chef-hostname.git
  ref: master
  sha: 082a2d3f3f190dac4258eee1603eb03eb2a662fd
  specs:
    hostname (0.0.2)
      route53 (>= 0.0.0)

GIT
  remote: git@github.com:CXInc/chef-munin.git
  ref: master
  sha: 0ca8ed0b94438b28e06c9171a52cec1e4db1da80
  specs:
    munin (1.0.0)
      apache2 (>= 1.0.6)
      perl (>= 0.0.0)

GIT
  remote: git@github.com:CXInc/chef-nagios.git
  ref: master
  sha: ef7cafee264020cdc36d10e20507d552a166ac96
  specs:
    nagios (1.0.5)
      apache2 (>= 0.0.0)
      build-essential (>= 0.0.0)
      php (>= 0.0.0)

GIT
  remote: git@github.com:CXInc/chef-percona-install.git
  ref: master
  sha: 7a26df8cb392e76d3c801afac08a2f841edab577
  specs:
    percona-install (0.0.5)

GIT
  remote: git@github.com:CXInc/chef-php-fpm.git
  ref: master
  sha: 43c96e09db2bf4e3b428523eeaf57fc81693fc05
  specs:
    php-fpm (0.1.0)
      php (>= 0.0.0)

GIT
  remote: git@github.com:CXInc/chef-rundeck.git
  ref: master
  sha: 7fa361d78e1e32be8cd39061ed5030df770ab03d
  specs:
    rundeck (0.0.2)
      java (>= 0.0.0)
      rvm (>= 0.0.0)

GIT
  remote: git@github.com:CXInc/chef-s3cmd_logs.git
  ref: master
  sha: 2b936024979ad6f22c3c4da4a9c1754fe5c1ccde
  specs:
    s3cmd_logs (0.0.1)

GIT
  remote: git@github.com:CXInc/chef-ssh_known_hosts.git
  ref: master
  sha: 7ee26008156fc3cb65ce3201730b77936f4d9f8a
  specs:
    ssh_known_hosts (0.3.1)

GIT
  remote: git@github.com:CXInc/chef-stud.git
  ref: master
  sha: cd45c486ed945ba4d732bcb92392bf52bca35e91
  specs:
    stud (0.0.3)
      build-essential (>= 0.0.0)
      git (>= 0.0.0)
      runit (>= 0.0.0)

GIT
  remote: git@github.com:CXInc/chef-users.git
  ref: master
  sha: 53cad1f8265b03ba10fc717e340f825490201a0e
  specs:
    users (1.0.1)

GIT
  remote: git@github.com:CXInc/chef-wordpress.git
  ref: master
  sha: 03f2babb53ea22b9a63239b6692ac487cad904da
  specs:
    wordpress (0.8.8)
      apache2 (>= 0.99.4)
      git (>= 0.0.0)
      mysql (>= 1.0.5)
      nginx (>= 0.99.0)
      openssl (>= 0.0.0)
      php (>= 0.0.0)
      php-fpm (>= 0.1.0)

GIT
  remote: https://github.com/fnichol/chef-jenkins
  ref: v0.5
  sha: 3fc6a56e6d40d8229afe301b4eee460d9537f0aa
  specs:
    jenkins (0.5.0)
      iptables (>= 0.0.0)
      java (>= 0.0.0)
      runit (>= 0.0.0)

GIT
  remote: https://github.com/fnichol/chef-rvm
  ref: v0.8.6
  sha: f5b89cb4dafa261afb5b18c4d0936aaf302e2a15
  specs:
    rvm (0.8.6)

DEPENDENCIES
  apache2 (>= 0)
  application (>= 0)
  apt (>= 0)
  aws (>= 0)
  build-essential (>= 0)
  chef-client (>= 0)
  chef-cxapi (>= 0)
  chef-server (>= 0)
  chef_handler (>= 0)
  couchdb (>= 0)
  cron (>= 0)
  cxdb (>= 0)
  cxror (>= 0)
  cxvpn (>= 0)
  database (>= 0)
  elasticsearch (>= 0)
  erlang (>= 0)
  git (>= 0)
  graylog2 (>= 0)
  haproxy (>= 0)
  hostname (>= 0)
  java (>= 0)
  jenkins (>= 0)
  logrotate (>= 0)
  logstash (>= 0)
  memcached (>= 0)
  munin (>= 0)
  mysql (>= 0)
  nagios (>= 0)
  nginx (>= 0)
  ntp (>= 0)
  ohai (>= 0)
  openssh (>= 0)
  openssl (>= 0)
  openvpn (>= 0)
  percona-install (>= 0)
  perl (>= 0)
  php (>= 0)
  php-fpm (>= 0)
  postfix (>= 0)
  python (>= 0)
  rabbitmq (>= 0)
  rabbitmq_chef (>= 0)
  route53 (>= 0)
  rsync (>= 0)
  rsyslog (>= 0)
  rundeck (>= 0)
  runit (>= 0)
  rvm (>= 0)
  s3cmd_logs (>= 0)
  sensu (>= 0)
  solr (>= 0)
  ssh_known_hosts (>= 0)
  stud (>= 0)
  sudo (>= 0)
  sysctl (>= 0)
  tmux (>= 0)
  ucspi-tcp (>= 0)
  users (>= 0)
  varnish (>= 0)
  vim (>= 0)
  wordpress (>= 0)
  xfs (>= 0)
  xml (>= 0)
  yum (>= 0)
  zlib (>= 0)
  zookeeper (>= 0)

**Comment by yfeldblum** [comment]
Is this fixed in 0.0.17 or is this still a problem?

**Comment by apeshimam** [comment]
Looks like 0.0.17 fixed this. Thanks!
