### ISSUE TITLE
Doc using :git and :path together

### ISSUE THREAD

**Issue by patcon** [applicationsonline/librarian#58]
Think I must have learned it was possible in an IRC or issue convo, but just realized that using `:git` and `:path` together for chef-repo-style cookbook repositories isn't documented or obvious. Will try to submit a patch when I think about it.

**Comment by yfeldblum** [comment]
It is currently documented in the readme.

I added it in commit a19f6ed5c05f4ce4b0ef5524f86c2cbd505e51f6, as of 2012-04-04.

However, the documentation can always use some more eyes and some more hands.

**Comment by patcon** [comment]
Sorry Jay, skimmed it before but must have missed it!
