### ISSUE TITLE
RubyGems page points to old version of docs

### ISSUE THREAD

**Issue by jtimberman** [applicationsonline/librarian#59]
The [RubyGems page](http://rubygems.org/gems/librarian) for Librarian points at the [0.0.1 version](http://rubydoc.info/gems/librarian/0.0.1/frames), instead of the latest [0.0.17](http://rubydoc.info/gems/librarian/0.0.17/frames).

**Comment by yfeldblum** [comment]
Fixed, thanks! The URL is now: http://rubydoc.info/gems/librarian/frames, which should always cover the latest released version.

It should be noted that the documented CLI commands and file formats are the only public API so far.

The the Librarian implementation should be considered as in flux, with the only authoritative source for information about the implementation being the code itself. Everything currently in the readme, though - including the specfile and lockfile formats - should not change and should remain supported.

If there's a specific need for building, supporting, and documenting specific hooks, though, that's certainly possible.
