### ISSUE TITLE
Eliminate Outbound Network connections when integrated into knife.rb

### ISSUE THREAD

**Issue by hh** [applicationsonline/librarian#67]
When I have this in my knife.rb:

``` ruby
begin
  require 'librarian/chef/integration/knife'
  cookbook_path Librarian::Chef.install_path, "#{current_dir}/../site-cookbooks"
rescue LoadError
  cookbook_path            "#{current_dir}/../cookbooks", "#{current_dir}/../site-cookbooks"
end
```

Running any knife commands result in outbound network connections related to the Cheffile.

If Cheffile and Cheffile.lock are current, librarian should make no network connections... it can slow things down considerably when your on a slow network connection.

**Comment by yfeldblum** [comment]
Is this resolved in 0.0.23?

**Comment by hh** [comment]
I'll test this tomorrow

**Comment by yfeldblum** [comment]
Closing because I believe it is fixed. If this is still an issue, feel free to reopen.
