### ISSUE TITLE
Gem Conflicts re Thor

### ISSUE THREAD

**Issue by yfeldblum** [applicationsonline/librarian#70]
Conflicts with veewee and sahara around the dependencies on thor.

We depend on `thor ~> 0.15`, while they depend on `thor ~> 0.14.6`.

Thor 0.15 adds useful features around subcommands and testability.

jedi4ever/veewee#307
jedi4ever/sahara#10

/cc @jedi4ever

**Comment by lukewpatterson** [comment]
I've run into this too.

**Comment by tknerr** [comment]
+1

**Comment by jedi4ever** [comment]
relaxed the thor version of sahara and released a new version.

**Comment by yfeldblum** [comment]
Bumped in veewee master as well.
