### ISSUE TITLE
US-ASCII (Encoding::InvalidByteSequenceError)

### ISSUE THREAD

**Issue by leehambley** [applicationsonline/librarian#71]
Short info (From IRC)

So with the following settings:

``` text
locale
LANG=
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL="C"
```

Installing the `firewall` cookbook from opscode doesn't work out, something about the encoding in the JSON file. When fixing my `locale` to `en_GB.UTF-8`, everything works as expected.

Ruby Version: 1.9.3-p194
Platform: Mac OSX 10.7
Shell: Z-Shell

When changing my `~/.zshrc` to export the `LC_ALL` variable, setting it to `en_GB.UTF-8` then everything worked as expected. I suspect the underlying issue is that the file opening commands don't use the optional encoding argument (e.g. `File.open('./path/to/some.file', 'r+:utf-8')`), and instead rely on the `Encoding.default_external`, which is `US-ASCII` when the `locale` is set to `C`.

**Comment by yfeldblum** [comment]
Can you provide an example? A gist including the files `Cheffile`, `Cheffile.lock` (if it exists), and the output of `librarian-chef install --verbose` so I can see the exception backtrace?

**Comment by leehambley** [comment]
Here's the `Cheffile`:

``` ruby
#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'build-essential'
cookbook 'cron'
cookbook 'denyhosts'
cookbook 'users'
cookbook 'git'
cookbook 'nginx'
cookbook 'openssl'
cookbook 'sudo'
cookbook 'timezone'
cookbook 'ufw'
cookbook 'unicorn'


cookbook 'postgresql',
  :git => 'https://github.com/findsyou/cookbooks',
  :ref => 'postgresql-improvements'

cookbook 'htop',
  :git => 'https://github.com/phlipper/chef-htop.git'

cookbook 'rbenv',
  :git => 'https://github.com/fnichol/chef-rbenv'

cookbook 'user',
  :git => 'git://github.com/fnichol/chef-user.git', :ref => 'v0.2.10'

cookbook 'ruby_build',
  :git => 'git://github.com/fnichol/chef-ruby_build.git', :ref => 'v0.6.2'
```

This is absolutely connected to the `locale` setting, when the locale is `C` (or rather anything that isn't `UTF-8`) Ruby assumes that it is opening files (`Encoding.default_external`) with an ASCII encoding, this can be overridden at the place the file is opened ([see here](http://stackoverflow.com/questions/1378185/how-to-specify-output-file-encoding-in-ruby)).

I actually can't replicate this now, since I've fixed my locale (exporting it doesn't seem to work, and I can't seem to break it anymore) but I got the same error from the knife tool, when doing `knife cook root@1.2.3.0.0.0 nodes/example.json` (`knife-solo` convenience wrapper)

`ERROR: RuntimeError: Syntax error in cookbooks/firewall/metadata.json: "\xC4" on US-ASCII`

Which is the same problem, the contents of this file are ASCII encoded (specifically the author name `thanks to Ernad Husremović for the fix.`)

I notice that the last release of librarian-chef was May 14th, it's entirely possible that this bug has gone away between 0.0.22 and 0.0.23 (is there an easy way to diff that stuff on Github?) ( I use rbenv gemsets, and recently moved from 1.9.3-p0 to 1.9.3-p194, so  either it's fixed by reinstalling Ruby, and upgrading 149 patch levels, or by accidentally getting a newer version of the librarian gem.)

All I can suggest is that in any place you open a file, do it by specifying the encoding as part of the readmode string (2nd argument)

Or, ignore me if you already fixed something in that vein :) (hope my "bug reports" are useful, I try to give enough detail, but I know with a million disparate configs in the wild it can be thankless trying to solve bugs the reporters cannot replicate!

**Comment by yfeldblum** [comment]
Here's the diff from [v0.0.22...v0.0.23](https://github.com/applicationsonline/librarian/compare/v0.0.22...v0.0.23).

**Comment by leehambley** [comment]
A quick search didn't show anything where you had changed the open mode of any files, I see you are using `wb` quite often, but that all seems to be for handling gzip/binary files.

Do you mind leaving the issue open, pending my making time to actually look a little deeper into this? If there's nothing in a week let's say that it's just user error and if anyone else finds the same problem, hopefully they'll come across this issue and re-open it for us?

**Comment by yfeldblum** [comment]
JSON is required to be Unicode. If a particular sequence of bytes is not legal in any of the Unicode encodings, then it is not legal JSON.

**Comment by leehambley** [comment]
That's true, but according to the encoding of the snippet I posted, it's encoded correctly (the byte sequence is `\xC4 \x87`).

**Comment by yfeldblum** [comment]
Any further results?

**Comment by leehambley** [comment]
I think it's clear, that when Ruby runs with a default external of US-ANSI as caused by `LC_ALL=c`, then the files won't open. I think you have to explicitly open the files with `r:utf-8` in order to guarantee that they are processable.

Fixing my system locale fixed the problem for me, but I think a locale of `c` is quite common, you might want to think about documenting that, warning about it when the locale is not compatible, or some other behaviour. My take is that with a sane locale (and I work in Germany, so having a UTF-8 locale is important to me, regardless. Switching to ZSH from Bash masked the problem that my locale override wasn't getting set)

**Comment by yfeldblum** [comment]
Does a2e86b142aaa3649f3514d72767787ed980dad42 fix this for you?
