### ISSUE TITLE
Split chef code out to separate 'plugin' or project

### ISSUE THREAD

**Issue by aussielunix** [applicationsonline/librarian#79]
G`Day all,  

I like the idea of Librarian but would love to see it become a build framework with 'plugins or adapters'
Could the chef code be extracted out and this become generic ?
This would make it much easier for others to build new Librarian 'adaptors' such as the work that @rodjek has in a pre-release stage. https://github.com/rodjek/librarian-puppet/tree/

Cheers
Mick
@aussielunix

**Comment by yfeldblum** [comment]
That's the goal of Librarian. It's not quite ready for that yet, since there needs to be some work put into splitting the CLI.
