### ISSUE TITLE
Use librarian in rake task?

### ISSUE THREAD

**Issue by thegcat** [applicationsonline/librarian#90]
Im trying to build a rake task to take care of the `librarian-chef install` and `vagrant up` steps, what would be the best/recommended way to execute "cli" steps without having to shell out?

**Comment by thegcat** [comment]
(bonus points if it can seamlessly integrated into `vagrant up` without the need for a rake task)

**Comment by cburyta** [comment]
(per rake task) I can't say I'm sure about it being the _best_ way, but "sh" has been working well for me. https://gist.github.com/3824824

**Comment by thegcat** [comment]
Not a big fan of having to shell out to execute ruby stuff from a rake task, but oh well.

**Comment by yfeldblum** [comment]
Librarian has been moving in the direction of having an API for which the CLI is a simple shell, but the work is not yet complete.

In the meantime, there is no supported or documented API. The only supported and documented pieces are the CLI. And even then, Librarian and Librarian-Chef are pre-1.0 so even their CLIs are likely to change over time.

**Comment by thegcat** [comment]
Closing here as I've scratched my own itch and made a vagrant plugin that will automatically install Librarian-managed cookbooks on `vagrant up` https://github.com/thegcat/vagrant-librarian
