### ISSUE TITLE
Documentation for gitignore is problematic

### ISSUE THREAD

**Issue by kesor** [applicationsonline/librarian#91]
The README shows how to add `cookbooks` to `.gitignore`, it also requires a line that says to NOT ignore `vendor/cookbooks` or git ignores that folder as well.

better version:

``` bash
echo cookbooks >> .gitignore
echo \!vendor/cookbooks >> .gitignore
```

**Comment by yfeldblum** [comment]
Why should `vendor/cookbooks` be gitignored?

**Comment by kesor** [comment]
it shouldn't, notice the exclamation at the line start.

**Comment by yfeldblum** [comment]
Gotcha. Ignoring `/cookbooks` rather than `cookbooks` should take care of that as well, right?

**Comment by kesor** [comment]
You are right, ignoring `/cookbooks` also works.
