### ISSUE TITLE
Support HTTP_PROXY.

### ISSUE THREAD

**Issue by yfeldblum** [applicationsonline/librarian#92]
The implementation of same [in rubygems](https://github.com/rubygems/rubygems/blob/v1.8.24/lib/rubygems/remote_fetcher.rb#L276-293).

**Comment by brandonzylstra** [comment]
I will try to work on this if/when I have a chance...

**Comment by yfeldblum** [comment]
Fixed by dbf23c040f6e6f4851bc42defc9b7b559ba98f18. Thanks @tknerr.

@brandondrew Does the latest master work for your case?
