### ISSUE TITLE
README confusing about cookbooks dir w/knife integration

### ISSUE THREAD

**Issue by jaylevitt** [applicationsonline/librarian#93]
First-day user here. I deleted my `chef-repo/cookbooks` directory, added it to .gitignore, and added librarian's integration into my knife.rb.

According to the docs, if I put `cookbook "chef-client"` into my Cheffile, I should see the following behavior:
1. When I do `librarian-chef install`, librarian will clone the upstream `chef-client` into `chef-repo/cookbooks/chef-client`
2. When I do `knife upload cookbooks --all`, librarian will copy those cookbooks into a temp directory and upload from there

I don't see the point of #2.. if cookbooks is managed by knife in the first place, why make a copy? If the idea is to prevent me manually adding or modifying cookbooks in /cookbooks, why not check for this?

**Comment by yfeldblum** [comment]
The purpose of the current knife integration is to help you enforce the policy that, when uploading cookbooks to a chef-server, you get the exact cookbooks specified in your `Cheffile.lock`.

If you want help enforcing this policy, e.g. against common or random mistakes or whatnot, then the knife integration can help you.

If you don't want help enforcing this policy, then you may prefer to ignore the knife integration.

**Comment by jaylevitt** [comment]
Ah, thanks. I was envisioning a much tighter integration, more like Bundler: cookbooks in the Cheffile automatically run ('require') their default recipe, the cookbooks get cached in a hidden subdirectory, etc.  Is that a long-term goal for Librarian, or is that something that you're hoping a complementary project will take on?

**Comment by yfeldblum** [comment]
There may be better ways out there to enforce that knife only uploads the exact cookbooks specified in your `Cheffile.lock`. The current implementation is just the current implementation.

I don't see librarian-chef loading cookbooks - that's what chef-client (or chef-solo or shef) does. Here, librarian-chef works more like `Bundler.setup` than `Bundler.require`.
