### ISSUE TITLE
Feature: get one cookbook from a collection

### ISSUE THREAD

**Issue by till** [applicationsonline/librarian#94]
I am trying to do this:

```
cookbook "bprobe",
  :git => "https://github.com/boundary/boundary_cookbooks"
```

My expectation was that this downloads the boundary cookbook from the repository. Instead it dies with "no metadata.rb found", which I think means that it expects the `boundary_cookbooks` repo to be just the bprobe cookbook.

**Comment by yfeldblum** [comment]
That should be supported, but try this:

```
cookbook "bprobe",
  :git => "https://github.com/boundary/boundary_cookbooks",
  :path => "bprobe"
```

**Comment by till** [comment]
@yfeldblum Thanks for replying. I didn't see this earlier!
