### ISSUE TITLE
Librarian failing with "Cheffile and Cheffile.lock are out of sync!"

### ISSUE THREAD

**Issue by rchampourlier** [applicationsonline/librarian#96]
Here is a [gist](https://gist.github.com/3302126) with the Cheffile and the `librarian-chef install --verbose` dump.

The failure happens as soon as I try to use the git version of the `postgresql` cookbook. When I turn back to the Community Opscode repo, it works again.

I can't get it to work even by reordering `database` and `postgresql` cookbooks, or removing the `database` one.

**Comment by yfeldblum** [comment]
`:ref => :master` should be `:ref => 'master'` with a string rather than a symbol.

**Comment by rchampourlier** [comment]
Arg, that's stupid. Sorry!

Thanks for answering this fast by the way.
